# Site settings
title: Wild Aye
description: "Photo Journal"
url: "https://wildaye.co.uk"
baseurl: ""
facebook_username: "wildayephotography"
instagram_username: "wild_aye"
# email: "kara@karamudie.co.uk"
twitter_username: "wild_aye"
github_username:  "wildaye"
# deviantart_username: ""
# flickr_username: ""
share: true

# Owner/author information
owner:
  name: Kara Hood
  avatar: avatar.png
  favicon: favicon.ico
  info: Photographer

# Internal nav
nav:
  - HOME: "/"
  - GALLERY: "/gallery/"  
  - JOURNAL: https://wildaye.substack.com/
  - ABOUT: "/about/"

collections:
  collections:
    sort_by: order
    output: true
    permalink: /:slug

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination: ./docs
port: 4000


# Build settings
markdown: kramdown
highlighter: rouge
# permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
plugins:
 - jekyll-paginate
 - jekyll-webp
exclude: 
  - "README.md"
  - "Rakefile"
  - vendor
  - bundle

webp:
  enabled: true
  quality: 75
  img_dir: ["/img/"]
  nested: true
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  regenerate: false

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
